// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

public interface CredentialsDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CredentialsDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string teamName = 2;</code>
   * @return The teamName.
   */
  java.lang.String getTeamName();
  /**
   * <code>string teamName = 2;</code>
   * @return The bytes for teamName.
   */
  com.google.protobuf.ByteString
      getTeamNameBytes();

  /**
   * <code>int32 capacity = 3;</code>
   * @return The capacity.
   */
  int getCapacity();
}
