// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

/**
 * Protobuf type {@code grpc.ParticipantDto}
 */
public final class ParticipantDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.ParticipantDto)
    ParticipantDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParticipantDto.newBuilder() to construct.
  private ParticipantDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParticipantDto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ParticipantDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ParticipantDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.Race.Builder subBuilder = null;
            if (race_ != null) {
              subBuilder = race_.toBuilder();
            }
            race_ = input.readMessage(grpc.Race.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(race_);
              race_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            grpc.Participant.Builder subBuilder = null;
            if (participant_ != null) {
              subBuilder = participant_.toBuilder();
            }
            participant_ = input.readMessage(grpc.Participant.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(participant_);
              participant_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.proto.internal_static_grpc_ParticipantDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.proto.internal_static_grpc_ParticipantDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ParticipantDto.class, grpc.ParticipantDto.Builder.class);
  }

  public static final int RACE_FIELD_NUMBER = 1;
  private grpc.Race race_;
  /**
   * <code>.grpc.Race race = 1;</code>
   * @return Whether the race field is set.
   */
  @java.lang.Override
  public boolean hasRace() {
    return race_ != null;
  }
  /**
   * <code>.grpc.Race race = 1;</code>
   * @return The race.
   */
  @java.lang.Override
  public grpc.Race getRace() {
    return race_ == null ? grpc.Race.getDefaultInstance() : race_;
  }
  /**
   * <code>.grpc.Race race = 1;</code>
   */
  @java.lang.Override
  public grpc.RaceOrBuilder getRaceOrBuilder() {
    return getRace();
  }

  public static final int PARTICIPANT_FIELD_NUMBER = 2;
  private grpc.Participant participant_;
  /**
   * <code>.grpc.Participant participant = 2;</code>
   * @return Whether the participant field is set.
   */
  @java.lang.Override
  public boolean hasParticipant() {
    return participant_ != null;
  }
  /**
   * <code>.grpc.Participant participant = 2;</code>
   * @return The participant.
   */
  @java.lang.Override
  public grpc.Participant getParticipant() {
    return participant_ == null ? grpc.Participant.getDefaultInstance() : participant_;
  }
  /**
   * <code>.grpc.Participant participant = 2;</code>
   */
  @java.lang.Override
  public grpc.ParticipantOrBuilder getParticipantOrBuilder() {
    return getParticipant();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (race_ != null) {
      output.writeMessage(1, getRace());
    }
    if (participant_ != null) {
      output.writeMessage(2, getParticipant());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (race_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRace());
    }
    if (participant_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getParticipant());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ParticipantDto)) {
      return super.equals(obj);
    }
    grpc.ParticipantDto other = (grpc.ParticipantDto) obj;

    if (hasRace() != other.hasRace()) return false;
    if (hasRace()) {
      if (!getRace()
          .equals(other.getRace())) return false;
    }
    if (hasParticipant() != other.hasParticipant()) return false;
    if (hasParticipant()) {
      if (!getParticipant()
          .equals(other.getParticipant())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRace()) {
      hash = (37 * hash) + RACE_FIELD_NUMBER;
      hash = (53 * hash) + getRace().hashCode();
    }
    if (hasParticipant()) {
      hash = (37 * hash) + PARTICIPANT_FIELD_NUMBER;
      hash = (53 * hash) + getParticipant().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ParticipantDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ParticipantDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ParticipantDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ParticipantDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ParticipantDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ParticipantDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ParticipantDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ParticipantDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ParticipantDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ParticipantDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ParticipantDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ParticipantDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ParticipantDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.ParticipantDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.ParticipantDto)
      grpc.ParticipantDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.proto.internal_static_grpc_ParticipantDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.proto.internal_static_grpc_ParticipantDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ParticipantDto.class, grpc.ParticipantDto.Builder.class);
    }

    // Construct using grpc.ParticipantDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (raceBuilder_ == null) {
        race_ = null;
      } else {
        race_ = null;
        raceBuilder_ = null;
      }
      if (participantBuilder_ == null) {
        participant_ = null;
      } else {
        participant_ = null;
        participantBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.proto.internal_static_grpc_ParticipantDto_descriptor;
    }

    @java.lang.Override
    public grpc.ParticipantDto getDefaultInstanceForType() {
      return grpc.ParticipantDto.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ParticipantDto build() {
      grpc.ParticipantDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ParticipantDto buildPartial() {
      grpc.ParticipantDto result = new grpc.ParticipantDto(this);
      if (raceBuilder_ == null) {
        result.race_ = race_;
      } else {
        result.race_ = raceBuilder_.build();
      }
      if (participantBuilder_ == null) {
        result.participant_ = participant_;
      } else {
        result.participant_ = participantBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ParticipantDto) {
        return mergeFrom((grpc.ParticipantDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ParticipantDto other) {
      if (other == grpc.ParticipantDto.getDefaultInstance()) return this;
      if (other.hasRace()) {
        mergeRace(other.getRace());
      }
      if (other.hasParticipant()) {
        mergeParticipant(other.getParticipant());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ParticipantDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ParticipantDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.Race race_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.Race, grpc.Race.Builder, grpc.RaceOrBuilder> raceBuilder_;
    /**
     * <code>.grpc.Race race = 1;</code>
     * @return Whether the race field is set.
     */
    public boolean hasRace() {
      return raceBuilder_ != null || race_ != null;
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     * @return The race.
     */
    public grpc.Race getRace() {
      if (raceBuilder_ == null) {
        return race_ == null ? grpc.Race.getDefaultInstance() : race_;
      } else {
        return raceBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    public Builder setRace(grpc.Race value) {
      if (raceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        race_ = value;
        onChanged();
      } else {
        raceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    public Builder setRace(
        grpc.Race.Builder builderForValue) {
      if (raceBuilder_ == null) {
        race_ = builderForValue.build();
        onChanged();
      } else {
        raceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    public Builder mergeRace(grpc.Race value) {
      if (raceBuilder_ == null) {
        if (race_ != null) {
          race_ =
            grpc.Race.newBuilder(race_).mergeFrom(value).buildPartial();
        } else {
          race_ = value;
        }
        onChanged();
      } else {
        raceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    public Builder clearRace() {
      if (raceBuilder_ == null) {
        race_ = null;
        onChanged();
      } else {
        race_ = null;
        raceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    public grpc.Race.Builder getRaceBuilder() {
      
      onChanged();
      return getRaceFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    public grpc.RaceOrBuilder getRaceOrBuilder() {
      if (raceBuilder_ != null) {
        return raceBuilder_.getMessageOrBuilder();
      } else {
        return race_ == null ?
            grpc.Race.getDefaultInstance() : race_;
      }
    }
    /**
     * <code>.grpc.Race race = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.Race, grpc.Race.Builder, grpc.RaceOrBuilder> 
        getRaceFieldBuilder() {
      if (raceBuilder_ == null) {
        raceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.Race, grpc.Race.Builder, grpc.RaceOrBuilder>(
                getRace(),
                getParentForChildren(),
                isClean());
        race_ = null;
      }
      return raceBuilder_;
    }

    private grpc.Participant participant_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.Participant, grpc.Participant.Builder, grpc.ParticipantOrBuilder> participantBuilder_;
    /**
     * <code>.grpc.Participant participant = 2;</code>
     * @return Whether the participant field is set.
     */
    public boolean hasParticipant() {
      return participantBuilder_ != null || participant_ != null;
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     * @return The participant.
     */
    public grpc.Participant getParticipant() {
      if (participantBuilder_ == null) {
        return participant_ == null ? grpc.Participant.getDefaultInstance() : participant_;
      } else {
        return participantBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    public Builder setParticipant(grpc.Participant value) {
      if (participantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        participant_ = value;
        onChanged();
      } else {
        participantBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    public Builder setParticipant(
        grpc.Participant.Builder builderForValue) {
      if (participantBuilder_ == null) {
        participant_ = builderForValue.build();
        onChanged();
      } else {
        participantBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    public Builder mergeParticipant(grpc.Participant value) {
      if (participantBuilder_ == null) {
        if (participant_ != null) {
          participant_ =
            grpc.Participant.newBuilder(participant_).mergeFrom(value).buildPartial();
        } else {
          participant_ = value;
        }
        onChanged();
      } else {
        participantBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    public Builder clearParticipant() {
      if (participantBuilder_ == null) {
        participant_ = null;
        onChanged();
      } else {
        participant_ = null;
        participantBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    public grpc.Participant.Builder getParticipantBuilder() {
      
      onChanged();
      return getParticipantFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    public grpc.ParticipantOrBuilder getParticipantOrBuilder() {
      if (participantBuilder_ != null) {
        return participantBuilder_.getMessageOrBuilder();
      } else {
        return participant_ == null ?
            grpc.Participant.getDefaultInstance() : participant_;
      }
    }
    /**
     * <code>.grpc.Participant participant = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.Participant, grpc.Participant.Builder, grpc.ParticipantOrBuilder> 
        getParticipantFieldBuilder() {
      if (participantBuilder_ == null) {
        participantBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.Participant, grpc.Participant.Builder, grpc.ParticipantOrBuilder>(
                getParticipant(),
                getParentForChildren(),
                isClean());
        participant_ = null;
      }
      return participantBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.ParticipantDto)
  }

  // @@protoc_insertion_point(class_scope:grpc.ParticipantDto)
  private static final grpc.ParticipantDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ParticipantDto();
  }

  public static grpc.ParticipantDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParticipantDto>
      PARSER = new com.google.protobuf.AbstractParser<ParticipantDto>() {
    @java.lang.Override
    public ParticipantDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ParticipantDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParticipantDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParticipantDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ParticipantDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

