// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

public interface ParticipantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Participant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 raceId = 2;</code>
   * @return The raceId.
   */
  int getRaceId();

  /**
   * <code>int32 teamId = 3;</code>
   * @return The teamId.
   */
  int getTeamId();

  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
