// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

public interface ParticipantDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ParticipantDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Race race = 1;</code>
   * @return Whether the race field is set.
   */
  boolean hasRace();
  /**
   * <code>.grpc.Race race = 1;</code>
   * @return The race.
   */
  grpc.Race getRace();
  /**
   * <code>.grpc.Race race = 1;</code>
   */
  grpc.RaceOrBuilder getRaceOrBuilder();

  /**
   * <code>.grpc.Participant participant = 2;</code>
   * @return Whether the participant field is set.
   */
  boolean hasParticipant();
  /**
   * <code>.grpc.Participant participant = 2;</code>
   * @return The participant.
   */
  grpc.Participant getParticipant();
  /**
   * <code>.grpc.Participant participant = 2;</code>
   */
  grpc.ParticipantOrBuilder getParticipantOrBuilder();
}
