// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

public interface RaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Race)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 capacity = 2;</code>
   * @return The capacity.
   */
  int getCapacity();
}
