// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

public interface RaceDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.RaceDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Race race = 1;</code>
   * @return Whether the race field is set.
   */
  boolean hasRace();
  /**
   * <code>.grpc.Race race = 1;</code>
   * @return The race.
   */
  grpc.Race getRace();
  /**
   * <code>.grpc.Race race = 1;</code>
   */
  grpc.RaceOrBuilder getRaceOrBuilder();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
