// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

/**
 * Protobuf type {@code grpc.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    type_ = 0;
    error_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            grpc.UserDto.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((grpc.UserDto) data_).toBuilder();
            }
            data_ =
                input.readMessage(grpc.UserDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((grpc.UserDto) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 24: {
            dataCase_ = 3;
            data_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            dataCase_ = 4;
            data_ = s;
            break;
          }
          case 42: {
            grpc.CredentialsDto.Builder subBuilder = null;
            if (dataCase_ == 5) {
              subBuilder = ((grpc.CredentialsDto) data_).toBuilder();
            }
            data_ =
                input.readMessage(grpc.CredentialsDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((grpc.CredentialsDto) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 5;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            error_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.proto.internal_static_grpc_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.proto.internal_static_grpc_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.Request.class, grpc.Request.Builder.class);
  }

  /**
   * Protobuf enum {@code grpc.Request.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <code>GET_RACES = 1;</code>
     */
    GET_RACES(1),
    /**
     * <code>SEARCH_RACES = 2;</code>
     */
    SEARCH_RACES(2),
    /**
     * <code>FILTER_RACES = 3;</code>
     */
    FILTER_RACES(3),
    /**
     * <code>GET_PARTICIPANTS = 4;</code>
     */
    GET_PARTICIPANTS(4),
    /**
     * <code>REGISTER = 5;</code>
     */
    REGISTER(5),
    /**
     * <code>LOGOUT = 6;</code>
     */
    LOGOUT(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>GET_RACES = 1;</code>
     */
    public static final int GET_RACES_VALUE = 1;
    /**
     * <code>SEARCH_RACES = 2;</code>
     */
    public static final int SEARCH_RACES_VALUE = 2;
    /**
     * <code>FILTER_RACES = 3;</code>
     */
    public static final int FILTER_RACES_VALUE = 3;
    /**
     * <code>GET_PARTICIPANTS = 4;</code>
     */
    public static final int GET_PARTICIPANTS_VALUE = 4;
    /**
     * <code>REGISTER = 5;</code>
     */
    public static final int REGISTER_VALUE = 5;
    /**
     * <code>LOGOUT = 6;</code>
     */
    public static final int LOGOUT_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return GET_RACES;
        case 2: return SEARCH_RACES;
        case 3: return FILTER_RACES;
        case 4: return GET_PARTICIPANTS;
        case 5: return REGISTER;
        case 6: return LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.Request.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:grpc.Request.RequestType)
  }

  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    USERDTO(2),
    CAPACITY(3),
    TEAMNAME(4),
    CREDENTIALSDTO(5),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return USERDTO;
        case 3: return CAPACITY;
        case 4: return TEAMNAME;
        case 5: return CREDENTIALSDTO;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.grpc.Request.RequestType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.grpc.Request.RequestType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public grpc.Request.RequestType getType() {
    @SuppressWarnings("deprecation")
    grpc.Request.RequestType result = grpc.Request.RequestType.valueOf(type_);
    return result == null ? grpc.Request.RequestType.UNRECOGNIZED : result;
  }

  public static final int USERDTO_FIELD_NUMBER = 2;
  /**
   * <code>.grpc.UserDto userDto = 2;</code>
   * @return Whether the userDto field is set.
   */
  @java.lang.Override
  public boolean hasUserDto() {
    return dataCase_ == 2;
  }
  /**
   * <code>.grpc.UserDto userDto = 2;</code>
   * @return The userDto.
   */
  @java.lang.Override
  public grpc.UserDto getUserDto() {
    if (dataCase_ == 2) {
       return (grpc.UserDto) data_;
    }
    return grpc.UserDto.getDefaultInstance();
  }
  /**
   * <code>.grpc.UserDto userDto = 2;</code>
   */
  @java.lang.Override
  public grpc.UserDtoOrBuilder getUserDtoOrBuilder() {
    if (dataCase_ == 2) {
       return (grpc.UserDto) data_;
    }
    return grpc.UserDto.getDefaultInstance();
  }

  public static final int CAPACITY_FIELD_NUMBER = 3;
  /**
   * <code>int32 capacity = 3;</code>
   * @return Whether the capacity field is set.
   */
  @java.lang.Override
  public boolean hasCapacity() {
    return dataCase_ == 3;
  }
  /**
   * <code>int32 capacity = 3;</code>
   * @return The capacity.
   */
  @java.lang.Override
  public int getCapacity() {
    if (dataCase_ == 3) {
      return (java.lang.Integer) data_;
    }
    return 0;
  }

  public static final int TEAMNAME_FIELD_NUMBER = 4;
  /**
   * <code>string teamName = 4;</code>
   * @return Whether the teamName field is set.
   */
  public boolean hasTeamName() {
    return dataCase_ == 4;
  }
  /**
   * <code>string teamName = 4;</code>
   * @return The teamName.
   */
  public java.lang.String getTeamName() {
    java.lang.Object ref = "";
    if (dataCase_ == 4) {
      ref = data_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (dataCase_ == 4) {
        data_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string teamName = 4;</code>
   * @return The bytes for teamName.
   */
  public com.google.protobuf.ByteString
      getTeamNameBytes() {
    java.lang.Object ref = "";
    if (dataCase_ == 4) {
      ref = data_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (dataCase_ == 4) {
        data_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDENTIALSDTO_FIELD_NUMBER = 5;
  /**
   * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
   * @return Whether the credentialsDto field is set.
   */
  @java.lang.Override
  public boolean hasCredentialsDto() {
    return dataCase_ == 5;
  }
  /**
   * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
   * @return The credentialsDto.
   */
  @java.lang.Override
  public grpc.CredentialsDto getCredentialsDto() {
    if (dataCase_ == 5) {
       return (grpc.CredentialsDto) data_;
    }
    return grpc.CredentialsDto.getDefaultInstance();
  }
  /**
   * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
   */
  @java.lang.Override
  public grpc.CredentialsDtoOrBuilder getCredentialsDtoOrBuilder() {
    if (dataCase_ == 5) {
       return (grpc.CredentialsDto) data_;
    }
    return grpc.CredentialsDto.getDefaultInstance();
  }

  public static final int ERROR_FIELD_NUMBER = 6;
  private volatile java.lang.Object error_;
  /**
   * <code>string error = 6;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 6;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != grpc.Request.RequestType.LOGIN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (grpc.UserDto) data_);
    }
    if (dataCase_ == 3) {
      output.writeInt32(
          3, (int)((java.lang.Integer) data_));
    }
    if (dataCase_ == 4) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
    }
    if (dataCase_ == 5) {
      output.writeMessage(5, (grpc.CredentialsDto) data_);
    }
    if (!getErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, error_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != grpc.Request.RequestType.LOGIN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (grpc.UserDto) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            3, (int)((java.lang.Integer) data_));
    }
    if (dataCase_ == 4) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
    }
    if (dataCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (grpc.CredentialsDto) data_);
    }
    if (!getErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, error_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.Request)) {
      return super.equals(obj);
    }
    grpc.Request other = (grpc.Request) obj;

    if (type_ != other.type_) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 2:
        if (!getUserDto()
            .equals(other.getUserDto())) return false;
        break;
      case 3:
        if (getCapacity()
            != other.getCapacity()) return false;
        break;
      case 4:
        if (!getTeamName()
            .equals(other.getTeamName())) return false;
        break;
      case 5:
        if (!getCredentialsDto()
            .equals(other.getCredentialsDto())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + USERDTO_FIELD_NUMBER;
        hash = (53 * hash) + getUserDto().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CAPACITY_FIELD_NUMBER;
        hash = (53 * hash) + getCapacity();
        break;
      case 4:
        hash = (37 * hash) + TEAMNAME_FIELD_NUMBER;
        hash = (53 * hash) + getTeamName().hashCode();
        break;
      case 5:
        hash = (37 * hash) + CREDENTIALSDTO_FIELD_NUMBER;
        hash = (53 * hash) + getCredentialsDto().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.Request)
      grpc.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.proto.internal_static_grpc_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.proto.internal_static_grpc_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Request.class, grpc.Request.Builder.class);
    }

    // Construct using grpc.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      error_ = "";

      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.proto.internal_static_grpc_Request_descriptor;
    }

    @java.lang.Override
    public grpc.Request getDefaultInstanceForType() {
      return grpc.Request.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.Request build() {
      grpc.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.Request buildPartial() {
      grpc.Request result = new grpc.Request(this);
      result.type_ = type_;
      if (dataCase_ == 2) {
        if (userDtoBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = userDtoBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        result.data_ = data_;
      }
      if (dataCase_ == 4) {
        result.data_ = data_;
      }
      if (dataCase_ == 5) {
        if (credentialsDtoBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = credentialsDtoBuilder_.build();
        }
      }
      result.error_ = error_;
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.Request) {
        return mergeFrom((grpc.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.Request other) {
      if (other == grpc.Request.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      switch (other.getDataCase()) {
        case USERDTO: {
          mergeUserDto(other.getUserDto());
          break;
        }
        case CAPACITY: {
          setCapacity(other.getCapacity());
          break;
        }
        case TEAMNAME: {
          dataCase_ = 4;
          data_ = other.data_;
          onChanged();
          break;
        }
        case CREDENTIALSDTO: {
          mergeCredentialsDto(other.getCredentialsDto());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.grpc.Request.RequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.grpc.Request.RequestType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.Request.RequestType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public grpc.Request.RequestType getType() {
      @SuppressWarnings("deprecation")
      grpc.Request.RequestType result = grpc.Request.RequestType.valueOf(type_);
      return result == null ? grpc.Request.RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.Request.RequestType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(grpc.Request.RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.Request.RequestType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.UserDto, grpc.UserDto.Builder, grpc.UserDtoOrBuilder> userDtoBuilder_;
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     * @return Whether the userDto field is set.
     */
    @java.lang.Override
    public boolean hasUserDto() {
      return dataCase_ == 2;
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     * @return The userDto.
     */
    @java.lang.Override
    public grpc.UserDto getUserDto() {
      if (userDtoBuilder_ == null) {
        if (dataCase_ == 2) {
          return (grpc.UserDto) data_;
        }
        return grpc.UserDto.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return userDtoBuilder_.getMessage();
        }
        return grpc.UserDto.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    public Builder setUserDto(grpc.UserDto value) {
      if (userDtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        userDtoBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    public Builder setUserDto(
        grpc.UserDto.Builder builderForValue) {
      if (userDtoBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        userDtoBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    public Builder mergeUserDto(grpc.UserDto value) {
      if (userDtoBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != grpc.UserDto.getDefaultInstance()) {
          data_ = grpc.UserDto.newBuilder((grpc.UserDto) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          userDtoBuilder_.mergeFrom(value);
        }
        userDtoBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    public Builder clearUserDto() {
      if (userDtoBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        userDtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    public grpc.UserDto.Builder getUserDtoBuilder() {
      return getUserDtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    @java.lang.Override
    public grpc.UserDtoOrBuilder getUserDtoOrBuilder() {
      if ((dataCase_ == 2) && (userDtoBuilder_ != null)) {
        return userDtoBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (grpc.UserDto) data_;
        }
        return grpc.UserDto.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.UserDto userDto = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.UserDto, grpc.UserDto.Builder, grpc.UserDtoOrBuilder> 
        getUserDtoFieldBuilder() {
      if (userDtoBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = grpc.UserDto.getDefaultInstance();
        }
        userDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.UserDto, grpc.UserDto.Builder, grpc.UserDtoOrBuilder>(
                (grpc.UserDto) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return userDtoBuilder_;
    }

    /**
     * <code>int32 capacity = 3;</code>
     * @return Whether the capacity field is set.
     */
    public boolean hasCapacity() {
      return dataCase_ == 3;
    }
    /**
     * <code>int32 capacity = 3;</code>
     * @return The capacity.
     */
    public int getCapacity() {
      if (dataCase_ == 3) {
        return (java.lang.Integer) data_;
      }
      return 0;
    }
    /**
     * <code>int32 capacity = 3;</code>
     * @param value The capacity to set.
     * @return This builder for chaining.
     */
    public Builder setCapacity(int value) {
      dataCase_ = 3;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 capacity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCapacity() {
      if (dataCase_ == 3) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string teamName = 4;</code>
     * @return Whether the teamName field is set.
     */
    @java.lang.Override
    public boolean hasTeamName() {
      return dataCase_ == 4;
    }
    /**
     * <code>string teamName = 4;</code>
     * @return The teamName.
     */
    @java.lang.Override
    public java.lang.String getTeamName() {
      java.lang.Object ref = "";
      if (dataCase_ == 4) {
        ref = data_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (dataCase_ == 4) {
          data_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string teamName = 4;</code>
     * @return The bytes for teamName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTeamNameBytes() {
      java.lang.Object ref = "";
      if (dataCase_ == 4) {
        ref = data_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (dataCase_ == 4) {
          data_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string teamName = 4;</code>
     * @param value The teamName to set.
     * @return This builder for chaining.
     */
    public Builder setTeamName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 4;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string teamName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeamName() {
      if (dataCase_ == 4) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string teamName = 4;</code>
     * @param value The bytes for teamName to set.
     * @return This builder for chaining.
     */
    public Builder setTeamNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      dataCase_ = 4;
      data_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.CredentialsDto, grpc.CredentialsDto.Builder, grpc.CredentialsDtoOrBuilder> credentialsDtoBuilder_;
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     * @return Whether the credentialsDto field is set.
     */
    @java.lang.Override
    public boolean hasCredentialsDto() {
      return dataCase_ == 5;
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     * @return The credentialsDto.
     */
    @java.lang.Override
    public grpc.CredentialsDto getCredentialsDto() {
      if (credentialsDtoBuilder_ == null) {
        if (dataCase_ == 5) {
          return (grpc.CredentialsDto) data_;
        }
        return grpc.CredentialsDto.getDefaultInstance();
      } else {
        if (dataCase_ == 5) {
          return credentialsDtoBuilder_.getMessage();
        }
        return grpc.CredentialsDto.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    public Builder setCredentialsDto(grpc.CredentialsDto value) {
      if (credentialsDtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        credentialsDtoBuilder_.setMessage(value);
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    public Builder setCredentialsDto(
        grpc.CredentialsDto.Builder builderForValue) {
      if (credentialsDtoBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        credentialsDtoBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    public Builder mergeCredentialsDto(grpc.CredentialsDto value) {
      if (credentialsDtoBuilder_ == null) {
        if (dataCase_ == 5 &&
            data_ != grpc.CredentialsDto.getDefaultInstance()) {
          data_ = grpc.CredentialsDto.newBuilder((grpc.CredentialsDto) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 5) {
          credentialsDtoBuilder_.mergeFrom(value);
        }
        credentialsDtoBuilder_.setMessage(value);
      }
      dataCase_ = 5;
      return this;
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    public Builder clearCredentialsDto() {
      if (credentialsDtoBuilder_ == null) {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
        }
        credentialsDtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    public grpc.CredentialsDto.Builder getCredentialsDtoBuilder() {
      return getCredentialsDtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    @java.lang.Override
    public grpc.CredentialsDtoOrBuilder getCredentialsDtoOrBuilder() {
      if ((dataCase_ == 5) && (credentialsDtoBuilder_ != null)) {
        return credentialsDtoBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 5) {
          return (grpc.CredentialsDto) data_;
        }
        return grpc.CredentialsDto.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.CredentialsDto credentialsDto = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.CredentialsDto, grpc.CredentialsDto.Builder, grpc.CredentialsDtoOrBuilder> 
        getCredentialsDtoFieldBuilder() {
      if (credentialsDtoBuilder_ == null) {
        if (!(dataCase_ == 5)) {
          data_ = grpc.CredentialsDto.getDefaultInstance();
        }
        credentialsDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.CredentialsDto, grpc.CredentialsDto.Builder, grpc.CredentialsDtoOrBuilder>(
                (grpc.CredentialsDto) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 5;
      onChanged();;
      return credentialsDtoBuilder_;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 6;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 6;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 6;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>string error = 6;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.Request)
  }

  // @@protoc_insertion_point(class_scope:grpc.Request)
  private static final grpc.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.Request();
  }

  public static grpc.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

