// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc.Response.ResponseType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.grpc.Response.ResponseType type = 1;</code>
   * @return The type.
   */
  grpc.Response.ResponseType getType();

  /**
   * <code>.grpc.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.grpc.User user = 2;</code>
   * @return The user.
   */
  grpc.User getUser();
  /**
   * <code>.grpc.User user = 2;</code>
   */
  grpc.UserOrBuilder getUserOrBuilder();

  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  java.util.List<grpc.Race> 
      getRacesList();
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  grpc.Race getRaces(int index);
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  int getRacesCount();
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  java.util.List<? extends grpc.RaceOrBuilder> 
      getRacesOrBuilderList();
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  grpc.RaceOrBuilder getRacesOrBuilder(
      int index);

  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  java.util.List<grpc.RaceDto> 
      getRaceDtosList();
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  grpc.RaceDto getRaceDtos(int index);
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  int getRaceDtosCount();
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  java.util.List<? extends grpc.RaceDtoOrBuilder> 
      getRaceDtosOrBuilderList();
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  grpc.RaceDtoOrBuilder getRaceDtosOrBuilder(
      int index);

  /**
   * <code>.grpc.RaceDto raceDto = 5;</code>
   * @return Whether the raceDto field is set.
   */
  boolean hasRaceDto();
  /**
   * <code>.grpc.RaceDto raceDto = 5;</code>
   * @return The raceDto.
   */
  grpc.RaceDto getRaceDto();
  /**
   * <code>.grpc.RaceDto raceDto = 5;</code>
   */
  grpc.RaceDtoOrBuilder getRaceDtoOrBuilder();

  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  java.util.List<grpc.ParticipantDto> 
      getParticipantsList();
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  grpc.ParticipantDto getParticipants(int index);
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  int getParticipantsCount();
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  java.util.List<? extends grpc.ParticipantDtoOrBuilder> 
      getParticipantsOrBuilderList();
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  grpc.ParticipantDtoOrBuilder getParticipantsOrBuilder(
      int index);

  /**
   * <code>string error = 7;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 7;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
