// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motorcycle.proto

package grpc;

/**
 * Protobuf type {@code grpc.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    type_ = 0;
    races_ = java.util.Collections.emptyList();
    raceDtos_ = java.util.Collections.emptyList();
    participants_ = java.util.Collections.emptyList();
    error_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            grpc.User.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(grpc.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              races_ = new java.util.ArrayList<grpc.Race>();
              mutable_bitField0_ |= 0x00000001;
            }
            races_.add(
                input.readMessage(grpc.Race.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              raceDtos_ = new java.util.ArrayList<grpc.RaceDto>();
              mutable_bitField0_ |= 0x00000002;
            }
            raceDtos_.add(
                input.readMessage(grpc.RaceDto.parser(), extensionRegistry));
            break;
          }
          case 42: {
            grpc.RaceDto.Builder subBuilder = null;
            if (raceDto_ != null) {
              subBuilder = raceDto_.toBuilder();
            }
            raceDto_ = input.readMessage(grpc.RaceDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(raceDto_);
              raceDto_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              participants_ = new java.util.ArrayList<grpc.ParticipantDto>();
              mutable_bitField0_ |= 0x00000004;
            }
            participants_.add(
                input.readMessage(grpc.ParticipantDto.parser(), extensionRegistry));
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            error_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        races_ = java.util.Collections.unmodifiableList(races_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        raceDtos_ = java.util.Collections.unmodifiableList(raceDtos_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        participants_ = java.util.Collections.unmodifiableList(participants_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.proto.internal_static_grpc_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.proto.internal_static_grpc_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.Response.class, grpc.Response.Builder.class);
  }

  /**
   * Protobuf enum {@code grpc.Response.ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>ERROR = 1;</code>
     */
    ERROR(1),
    /**
     * <code>REGISTERED_PARTICIPANT = 2;</code>
     */
    REGISTERED_PARTICIPANT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>ERROR = 1;</code>
     */
    public static final int ERROR_VALUE = 1;
    /**
     * <code>REGISTERED_PARTICIPANT = 2;</code>
     */
    public static final int REGISTERED_PARTICIPANT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResponseType forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return ERROR;
        case 2: return REGISTERED_PARTICIPANT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.Response.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:grpc.Response.ResponseType)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.grpc.Response.ResponseType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.grpc.Response.ResponseType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public grpc.Response.ResponseType getType() {
    @SuppressWarnings("deprecation")
    grpc.Response.ResponseType result = grpc.Response.ResponseType.valueOf(type_);
    return result == null ? grpc.Response.ResponseType.UNRECOGNIZED : result;
  }

  public static final int USER_FIELD_NUMBER = 2;
  private grpc.User user_;
  /**
   * <code>.grpc.User user = 2;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.grpc.User user = 2;</code>
   * @return The user.
   */
  @java.lang.Override
  public grpc.User getUser() {
    return user_ == null ? grpc.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.grpc.User user = 2;</code>
   */
  @java.lang.Override
  public grpc.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int RACES_FIELD_NUMBER = 3;
  private java.util.List<grpc.Race> races_;
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.Race> getRacesList() {
    return races_;
  }
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.RaceOrBuilder> 
      getRacesOrBuilderList() {
    return races_;
  }
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  @java.lang.Override
  public int getRacesCount() {
    return races_.size();
  }
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  @java.lang.Override
  public grpc.Race getRaces(int index) {
    return races_.get(index);
  }
  /**
   * <code>repeated .grpc.Race races = 3;</code>
   */
  @java.lang.Override
  public grpc.RaceOrBuilder getRacesOrBuilder(
      int index) {
    return races_.get(index);
  }

  public static final int RACEDTOS_FIELD_NUMBER = 4;
  private java.util.List<grpc.RaceDto> raceDtos_;
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.RaceDto> getRaceDtosList() {
    return raceDtos_;
  }
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.RaceDtoOrBuilder> 
      getRaceDtosOrBuilderList() {
    return raceDtos_;
  }
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  @java.lang.Override
  public int getRaceDtosCount() {
    return raceDtos_.size();
  }
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  @java.lang.Override
  public grpc.RaceDto getRaceDtos(int index) {
    return raceDtos_.get(index);
  }
  /**
   * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
   */
  @java.lang.Override
  public grpc.RaceDtoOrBuilder getRaceDtosOrBuilder(
      int index) {
    return raceDtos_.get(index);
  }

  public static final int RACEDTO_FIELD_NUMBER = 5;
  private grpc.RaceDto raceDto_;
  /**
   * <code>.grpc.RaceDto raceDto = 5;</code>
   * @return Whether the raceDto field is set.
   */
  @java.lang.Override
  public boolean hasRaceDto() {
    return raceDto_ != null;
  }
  /**
   * <code>.grpc.RaceDto raceDto = 5;</code>
   * @return The raceDto.
   */
  @java.lang.Override
  public grpc.RaceDto getRaceDto() {
    return raceDto_ == null ? grpc.RaceDto.getDefaultInstance() : raceDto_;
  }
  /**
   * <code>.grpc.RaceDto raceDto = 5;</code>
   */
  @java.lang.Override
  public grpc.RaceDtoOrBuilder getRaceDtoOrBuilder() {
    return getRaceDto();
  }

  public static final int PARTICIPANTS_FIELD_NUMBER = 6;
  private java.util.List<grpc.ParticipantDto> participants_;
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.ParticipantDto> getParticipantsList() {
    return participants_;
  }
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.ParticipantDtoOrBuilder> 
      getParticipantsOrBuilderList() {
    return participants_;
  }
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  @java.lang.Override
  public int getParticipantsCount() {
    return participants_.size();
  }
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  @java.lang.Override
  public grpc.ParticipantDto getParticipants(int index) {
    return participants_.get(index);
  }
  /**
   * <code>repeated .grpc.ParticipantDto participants = 6;</code>
   */
  @java.lang.Override
  public grpc.ParticipantDtoOrBuilder getParticipantsOrBuilder(
      int index) {
    return participants_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 7;
  private volatile java.lang.Object error_;
  /**
   * <code>string error = 7;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 7;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != grpc.Response.ResponseType.OK.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (user_ != null) {
      output.writeMessage(2, getUser());
    }
    for (int i = 0; i < races_.size(); i++) {
      output.writeMessage(3, races_.get(i));
    }
    for (int i = 0; i < raceDtos_.size(); i++) {
      output.writeMessage(4, raceDtos_.get(i));
    }
    if (raceDto_ != null) {
      output.writeMessage(5, getRaceDto());
    }
    for (int i = 0; i < participants_.size(); i++) {
      output.writeMessage(6, participants_.get(i));
    }
    if (!getErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, error_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != grpc.Response.ResponseType.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUser());
    }
    for (int i = 0; i < races_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, races_.get(i));
    }
    for (int i = 0; i < raceDtos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, raceDtos_.get(i));
    }
    if (raceDto_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRaceDto());
    }
    for (int i = 0; i < participants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, participants_.get(i));
    }
    if (!getErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, error_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.Response)) {
      return super.equals(obj);
    }
    grpc.Response other = (grpc.Response) obj;

    if (type_ != other.type_) return false;
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!getRacesList()
        .equals(other.getRacesList())) return false;
    if (!getRaceDtosList()
        .equals(other.getRaceDtosList())) return false;
    if (hasRaceDto() != other.hasRaceDto()) return false;
    if (hasRaceDto()) {
      if (!getRaceDto()
          .equals(other.getRaceDto())) return false;
    }
    if (!getParticipantsList()
        .equals(other.getParticipantsList())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (getRacesCount() > 0) {
      hash = (37 * hash) + RACES_FIELD_NUMBER;
      hash = (53 * hash) + getRacesList().hashCode();
    }
    if (getRaceDtosCount() > 0) {
      hash = (37 * hash) + RACEDTOS_FIELD_NUMBER;
      hash = (53 * hash) + getRaceDtosList().hashCode();
    }
    if (hasRaceDto()) {
      hash = (37 * hash) + RACEDTO_FIELD_NUMBER;
      hash = (53 * hash) + getRaceDto().hashCode();
    }
    if (getParticipantsCount() > 0) {
      hash = (37 * hash) + PARTICIPANTS_FIELD_NUMBER;
      hash = (53 * hash) + getParticipantsList().hashCode();
    }
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.Response)
      grpc.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.proto.internal_static_grpc_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.proto.internal_static_grpc_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Response.class, grpc.Response.Builder.class);
    }

    // Construct using grpc.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRacesFieldBuilder();
        getRaceDtosFieldBuilder();
        getParticipantsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (racesBuilder_ == null) {
        races_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        racesBuilder_.clear();
      }
      if (raceDtosBuilder_ == null) {
        raceDtos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        raceDtosBuilder_.clear();
      }
      if (raceDtoBuilder_ == null) {
        raceDto_ = null;
      } else {
        raceDto_ = null;
        raceDtoBuilder_ = null;
      }
      if (participantsBuilder_ == null) {
        participants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        participantsBuilder_.clear();
      }
      error_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.proto.internal_static_grpc_Response_descriptor;
    }

    @java.lang.Override
    public grpc.Response getDefaultInstanceForType() {
      return grpc.Response.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.Response build() {
      grpc.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.Response buildPartial() {
      grpc.Response result = new grpc.Response(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (racesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          races_ = java.util.Collections.unmodifiableList(races_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.races_ = races_;
      } else {
        result.races_ = racesBuilder_.build();
      }
      if (raceDtosBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          raceDtos_ = java.util.Collections.unmodifiableList(raceDtos_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.raceDtos_ = raceDtos_;
      } else {
        result.raceDtos_ = raceDtosBuilder_.build();
      }
      if (raceDtoBuilder_ == null) {
        result.raceDto_ = raceDto_;
      } else {
        result.raceDto_ = raceDtoBuilder_.build();
      }
      if (participantsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          participants_ = java.util.Collections.unmodifiableList(participants_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.participants_ = participants_;
      } else {
        result.participants_ = participantsBuilder_.build();
      }
      result.error_ = error_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.Response) {
        return mergeFrom((grpc.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.Response other) {
      if (other == grpc.Response.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (racesBuilder_ == null) {
        if (!other.races_.isEmpty()) {
          if (races_.isEmpty()) {
            races_ = other.races_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRacesIsMutable();
            races_.addAll(other.races_);
          }
          onChanged();
        }
      } else {
        if (!other.races_.isEmpty()) {
          if (racesBuilder_.isEmpty()) {
            racesBuilder_.dispose();
            racesBuilder_ = null;
            races_ = other.races_;
            bitField0_ = (bitField0_ & ~0x00000001);
            racesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRacesFieldBuilder() : null;
          } else {
            racesBuilder_.addAllMessages(other.races_);
          }
        }
      }
      if (raceDtosBuilder_ == null) {
        if (!other.raceDtos_.isEmpty()) {
          if (raceDtos_.isEmpty()) {
            raceDtos_ = other.raceDtos_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRaceDtosIsMutable();
            raceDtos_.addAll(other.raceDtos_);
          }
          onChanged();
        }
      } else {
        if (!other.raceDtos_.isEmpty()) {
          if (raceDtosBuilder_.isEmpty()) {
            raceDtosBuilder_.dispose();
            raceDtosBuilder_ = null;
            raceDtos_ = other.raceDtos_;
            bitField0_ = (bitField0_ & ~0x00000002);
            raceDtosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRaceDtosFieldBuilder() : null;
          } else {
            raceDtosBuilder_.addAllMessages(other.raceDtos_);
          }
        }
      }
      if (other.hasRaceDto()) {
        mergeRaceDto(other.getRaceDto());
      }
      if (participantsBuilder_ == null) {
        if (!other.participants_.isEmpty()) {
          if (participants_.isEmpty()) {
            participants_ = other.participants_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParticipantsIsMutable();
            participants_.addAll(other.participants_);
          }
          onChanged();
        }
      } else {
        if (!other.participants_.isEmpty()) {
          if (participantsBuilder_.isEmpty()) {
            participantsBuilder_.dispose();
            participantsBuilder_ = null;
            participants_ = other.participants_;
            bitField0_ = (bitField0_ & ~0x00000004);
            participantsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParticipantsFieldBuilder() : null;
          } else {
            participantsBuilder_.addAllMessages(other.participants_);
          }
        }
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.grpc.Response.ResponseType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.grpc.Response.ResponseType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.Response.ResponseType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public grpc.Response.ResponseType getType() {
      @SuppressWarnings("deprecation")
      grpc.Response.ResponseType result = grpc.Response.ResponseType.valueOf(type_);
      return result == null ? grpc.Response.ResponseType.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.Response.ResponseType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(grpc.Response.ResponseType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.Response.ResponseType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private grpc.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.User, grpc.User.Builder, grpc.UserOrBuilder> userBuilder_;
    /**
     * <code>.grpc.User user = 2;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.grpc.User user = 2;</code>
     * @return The user.
     */
    public grpc.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? grpc.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    public Builder setUser(grpc.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    public Builder setUser(
        grpc.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    public Builder mergeUser(grpc.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            grpc.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    public grpc.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    public grpc.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            grpc.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.grpc.User user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.User, grpc.User.Builder, grpc.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.User, grpc.User.Builder, grpc.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.util.List<grpc.Race> races_ =
      java.util.Collections.emptyList();
    private void ensureRacesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        races_ = new java.util.ArrayList<grpc.Race>(races_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.Race, grpc.Race.Builder, grpc.RaceOrBuilder> racesBuilder_;

    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public java.util.List<grpc.Race> getRacesList() {
      if (racesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(races_);
      } else {
        return racesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public int getRacesCount() {
      if (racesBuilder_ == null) {
        return races_.size();
      } else {
        return racesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public grpc.Race getRaces(int index) {
      if (racesBuilder_ == null) {
        return races_.get(index);
      } else {
        return racesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder setRaces(
        int index, grpc.Race value) {
      if (racesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRacesIsMutable();
        races_.set(index, value);
        onChanged();
      } else {
        racesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder setRaces(
        int index, grpc.Race.Builder builderForValue) {
      if (racesBuilder_ == null) {
        ensureRacesIsMutable();
        races_.set(index, builderForValue.build());
        onChanged();
      } else {
        racesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder addRaces(grpc.Race value) {
      if (racesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRacesIsMutable();
        races_.add(value);
        onChanged();
      } else {
        racesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder addRaces(
        int index, grpc.Race value) {
      if (racesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRacesIsMutable();
        races_.add(index, value);
        onChanged();
      } else {
        racesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder addRaces(
        grpc.Race.Builder builderForValue) {
      if (racesBuilder_ == null) {
        ensureRacesIsMutable();
        races_.add(builderForValue.build());
        onChanged();
      } else {
        racesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder addRaces(
        int index, grpc.Race.Builder builderForValue) {
      if (racesBuilder_ == null) {
        ensureRacesIsMutable();
        races_.add(index, builderForValue.build());
        onChanged();
      } else {
        racesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder addAllRaces(
        java.lang.Iterable<? extends grpc.Race> values) {
      if (racesBuilder_ == null) {
        ensureRacesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, races_);
        onChanged();
      } else {
        racesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder clearRaces() {
      if (racesBuilder_ == null) {
        races_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        racesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public Builder removeRaces(int index) {
      if (racesBuilder_ == null) {
        ensureRacesIsMutable();
        races_.remove(index);
        onChanged();
      } else {
        racesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public grpc.Race.Builder getRacesBuilder(
        int index) {
      return getRacesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public grpc.RaceOrBuilder getRacesOrBuilder(
        int index) {
      if (racesBuilder_ == null) {
        return races_.get(index);  } else {
        return racesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public java.util.List<? extends grpc.RaceOrBuilder> 
         getRacesOrBuilderList() {
      if (racesBuilder_ != null) {
        return racesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(races_);
      }
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public grpc.Race.Builder addRacesBuilder() {
      return getRacesFieldBuilder().addBuilder(
          grpc.Race.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public grpc.Race.Builder addRacesBuilder(
        int index) {
      return getRacesFieldBuilder().addBuilder(
          index, grpc.Race.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.Race races = 3;</code>
     */
    public java.util.List<grpc.Race.Builder> 
         getRacesBuilderList() {
      return getRacesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.Race, grpc.Race.Builder, grpc.RaceOrBuilder> 
        getRacesFieldBuilder() {
      if (racesBuilder_ == null) {
        racesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.Race, grpc.Race.Builder, grpc.RaceOrBuilder>(
                races_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        races_ = null;
      }
      return racesBuilder_;
    }

    private java.util.List<grpc.RaceDto> raceDtos_ =
      java.util.Collections.emptyList();
    private void ensureRaceDtosIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        raceDtos_ = new java.util.ArrayList<grpc.RaceDto>(raceDtos_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.RaceDto, grpc.RaceDto.Builder, grpc.RaceDtoOrBuilder> raceDtosBuilder_;

    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public java.util.List<grpc.RaceDto> getRaceDtosList() {
      if (raceDtosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(raceDtos_);
      } else {
        return raceDtosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public int getRaceDtosCount() {
      if (raceDtosBuilder_ == null) {
        return raceDtos_.size();
      } else {
        return raceDtosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public grpc.RaceDto getRaceDtos(int index) {
      if (raceDtosBuilder_ == null) {
        return raceDtos_.get(index);
      } else {
        return raceDtosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder setRaceDtos(
        int index, grpc.RaceDto value) {
      if (raceDtosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRaceDtosIsMutable();
        raceDtos_.set(index, value);
        onChanged();
      } else {
        raceDtosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder setRaceDtos(
        int index, grpc.RaceDto.Builder builderForValue) {
      if (raceDtosBuilder_ == null) {
        ensureRaceDtosIsMutable();
        raceDtos_.set(index, builderForValue.build());
        onChanged();
      } else {
        raceDtosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder addRaceDtos(grpc.RaceDto value) {
      if (raceDtosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRaceDtosIsMutable();
        raceDtos_.add(value);
        onChanged();
      } else {
        raceDtosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder addRaceDtos(
        int index, grpc.RaceDto value) {
      if (raceDtosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRaceDtosIsMutable();
        raceDtos_.add(index, value);
        onChanged();
      } else {
        raceDtosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder addRaceDtos(
        grpc.RaceDto.Builder builderForValue) {
      if (raceDtosBuilder_ == null) {
        ensureRaceDtosIsMutable();
        raceDtos_.add(builderForValue.build());
        onChanged();
      } else {
        raceDtosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder addRaceDtos(
        int index, grpc.RaceDto.Builder builderForValue) {
      if (raceDtosBuilder_ == null) {
        ensureRaceDtosIsMutable();
        raceDtos_.add(index, builderForValue.build());
        onChanged();
      } else {
        raceDtosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder addAllRaceDtos(
        java.lang.Iterable<? extends grpc.RaceDto> values) {
      if (raceDtosBuilder_ == null) {
        ensureRaceDtosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, raceDtos_);
        onChanged();
      } else {
        raceDtosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder clearRaceDtos() {
      if (raceDtosBuilder_ == null) {
        raceDtos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        raceDtosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public Builder removeRaceDtos(int index) {
      if (raceDtosBuilder_ == null) {
        ensureRaceDtosIsMutable();
        raceDtos_.remove(index);
        onChanged();
      } else {
        raceDtosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public grpc.RaceDto.Builder getRaceDtosBuilder(
        int index) {
      return getRaceDtosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public grpc.RaceDtoOrBuilder getRaceDtosOrBuilder(
        int index) {
      if (raceDtosBuilder_ == null) {
        return raceDtos_.get(index);  } else {
        return raceDtosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public java.util.List<? extends grpc.RaceDtoOrBuilder> 
         getRaceDtosOrBuilderList() {
      if (raceDtosBuilder_ != null) {
        return raceDtosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(raceDtos_);
      }
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public grpc.RaceDto.Builder addRaceDtosBuilder() {
      return getRaceDtosFieldBuilder().addBuilder(
          grpc.RaceDto.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public grpc.RaceDto.Builder addRaceDtosBuilder(
        int index) {
      return getRaceDtosFieldBuilder().addBuilder(
          index, grpc.RaceDto.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.RaceDto raceDtos = 4;</code>
     */
    public java.util.List<grpc.RaceDto.Builder> 
         getRaceDtosBuilderList() {
      return getRaceDtosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.RaceDto, grpc.RaceDto.Builder, grpc.RaceDtoOrBuilder> 
        getRaceDtosFieldBuilder() {
      if (raceDtosBuilder_ == null) {
        raceDtosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.RaceDto, grpc.RaceDto.Builder, grpc.RaceDtoOrBuilder>(
                raceDtos_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        raceDtos_ = null;
      }
      return raceDtosBuilder_;
    }

    private grpc.RaceDto raceDto_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.RaceDto, grpc.RaceDto.Builder, grpc.RaceDtoOrBuilder> raceDtoBuilder_;
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     * @return Whether the raceDto field is set.
     */
    public boolean hasRaceDto() {
      return raceDtoBuilder_ != null || raceDto_ != null;
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     * @return The raceDto.
     */
    public grpc.RaceDto getRaceDto() {
      if (raceDtoBuilder_ == null) {
        return raceDto_ == null ? grpc.RaceDto.getDefaultInstance() : raceDto_;
      } else {
        return raceDtoBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    public Builder setRaceDto(grpc.RaceDto value) {
      if (raceDtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        raceDto_ = value;
        onChanged();
      } else {
        raceDtoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    public Builder setRaceDto(
        grpc.RaceDto.Builder builderForValue) {
      if (raceDtoBuilder_ == null) {
        raceDto_ = builderForValue.build();
        onChanged();
      } else {
        raceDtoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    public Builder mergeRaceDto(grpc.RaceDto value) {
      if (raceDtoBuilder_ == null) {
        if (raceDto_ != null) {
          raceDto_ =
            grpc.RaceDto.newBuilder(raceDto_).mergeFrom(value).buildPartial();
        } else {
          raceDto_ = value;
        }
        onChanged();
      } else {
        raceDtoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    public Builder clearRaceDto() {
      if (raceDtoBuilder_ == null) {
        raceDto_ = null;
        onChanged();
      } else {
        raceDto_ = null;
        raceDtoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    public grpc.RaceDto.Builder getRaceDtoBuilder() {
      
      onChanged();
      return getRaceDtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    public grpc.RaceDtoOrBuilder getRaceDtoOrBuilder() {
      if (raceDtoBuilder_ != null) {
        return raceDtoBuilder_.getMessageOrBuilder();
      } else {
        return raceDto_ == null ?
            grpc.RaceDto.getDefaultInstance() : raceDto_;
      }
    }
    /**
     * <code>.grpc.RaceDto raceDto = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.RaceDto, grpc.RaceDto.Builder, grpc.RaceDtoOrBuilder> 
        getRaceDtoFieldBuilder() {
      if (raceDtoBuilder_ == null) {
        raceDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.RaceDto, grpc.RaceDto.Builder, grpc.RaceDtoOrBuilder>(
                getRaceDto(),
                getParentForChildren(),
                isClean());
        raceDto_ = null;
      }
      return raceDtoBuilder_;
    }

    private java.util.List<grpc.ParticipantDto> participants_ =
      java.util.Collections.emptyList();
    private void ensureParticipantsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        participants_ = new java.util.ArrayList<grpc.ParticipantDto>(participants_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.ParticipantDto, grpc.ParticipantDto.Builder, grpc.ParticipantDtoOrBuilder> participantsBuilder_;

    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public java.util.List<grpc.ParticipantDto> getParticipantsList() {
      if (participantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(participants_);
      } else {
        return participantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public int getParticipantsCount() {
      if (participantsBuilder_ == null) {
        return participants_.size();
      } else {
        return participantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public grpc.ParticipantDto getParticipants(int index) {
      if (participantsBuilder_ == null) {
        return participants_.get(index);
      } else {
        return participantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder setParticipants(
        int index, grpc.ParticipantDto value) {
      if (participantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParticipantsIsMutable();
        participants_.set(index, value);
        onChanged();
      } else {
        participantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder setParticipants(
        int index, grpc.ParticipantDto.Builder builderForValue) {
      if (participantsBuilder_ == null) {
        ensureParticipantsIsMutable();
        participants_.set(index, builderForValue.build());
        onChanged();
      } else {
        participantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder addParticipants(grpc.ParticipantDto value) {
      if (participantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParticipantsIsMutable();
        participants_.add(value);
        onChanged();
      } else {
        participantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder addParticipants(
        int index, grpc.ParticipantDto value) {
      if (participantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParticipantsIsMutable();
        participants_.add(index, value);
        onChanged();
      } else {
        participantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder addParticipants(
        grpc.ParticipantDto.Builder builderForValue) {
      if (participantsBuilder_ == null) {
        ensureParticipantsIsMutable();
        participants_.add(builderForValue.build());
        onChanged();
      } else {
        participantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder addParticipants(
        int index, grpc.ParticipantDto.Builder builderForValue) {
      if (participantsBuilder_ == null) {
        ensureParticipantsIsMutable();
        participants_.add(index, builderForValue.build());
        onChanged();
      } else {
        participantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder addAllParticipants(
        java.lang.Iterable<? extends grpc.ParticipantDto> values) {
      if (participantsBuilder_ == null) {
        ensureParticipantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, participants_);
        onChanged();
      } else {
        participantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder clearParticipants() {
      if (participantsBuilder_ == null) {
        participants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        participantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public Builder removeParticipants(int index) {
      if (participantsBuilder_ == null) {
        ensureParticipantsIsMutable();
        participants_.remove(index);
        onChanged();
      } else {
        participantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public grpc.ParticipantDto.Builder getParticipantsBuilder(
        int index) {
      return getParticipantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public grpc.ParticipantDtoOrBuilder getParticipantsOrBuilder(
        int index) {
      if (participantsBuilder_ == null) {
        return participants_.get(index);  } else {
        return participantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public java.util.List<? extends grpc.ParticipantDtoOrBuilder> 
         getParticipantsOrBuilderList() {
      if (participantsBuilder_ != null) {
        return participantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(participants_);
      }
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public grpc.ParticipantDto.Builder addParticipantsBuilder() {
      return getParticipantsFieldBuilder().addBuilder(
          grpc.ParticipantDto.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public grpc.ParticipantDto.Builder addParticipantsBuilder(
        int index) {
      return getParticipantsFieldBuilder().addBuilder(
          index, grpc.ParticipantDto.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.ParticipantDto participants = 6;</code>
     */
    public java.util.List<grpc.ParticipantDto.Builder> 
         getParticipantsBuilderList() {
      return getParticipantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.ParticipantDto, grpc.ParticipantDto.Builder, grpc.ParticipantDtoOrBuilder> 
        getParticipantsFieldBuilder() {
      if (participantsBuilder_ == null) {
        participantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.ParticipantDto, grpc.ParticipantDto.Builder, grpc.ParticipantDtoOrBuilder>(
                participants_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        participants_ = null;
      }
      return participantsBuilder_;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 7;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 7;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 7;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>string error = 7;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.Response)
  }

  // @@protoc_insertion_point(class_scope:grpc.Response)
  private static final grpc.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.Response();
  }

  public static grpc.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

